# Generated by Django 2.2.5 on 2019-10-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Htdocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('publishtime', models.DateTimeField(blank=True, null=True)),
                ('nlike', models.IntegerField(blank=True, null=True)),
                ('nreply', models.IntegerField(blank=True, null=True)),
                ('iscommercial', models.CharField(blank=True, max_length=5, null=True)),
                ('htmltext', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'htdocs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('publishtime', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('reporter', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('pcompany', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('htmltext', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naver_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bywhat', models.CharField(blank=True, db_column='ByWhat', max_length=200, null=True)),
                ('keywordA', models.CharField(blank=True, db_column='keywordA', max_length=200, null=True)),
                ('keywordB', models.CharField(blank=True, db_column='keywordB', max_length=200, null=True)),
                ('keywordC', models.CharField(blank=True, db_column='keywordC', max_length=200, null=True)),
                ('channelA', models.CharField(blank=True, db_column='channelA', max_length=200, null=True)),
                ('channelB', models.CharField(blank=True, db_column='channelB', max_length=200, null=True)),
                ('channelC', models.CharField(blank=True, db_column='channelC', max_length=200, null=True)),
                ('periodA', models.CharField(blank=True, db_column='periodA', max_length=200, null=True)),
                ('periodB', models.CharField(blank=True, db_column='periodB', max_length=200, null=True)),
                ('periodC', models.CharField(blank=True, db_column='periodC', max_length=200, null=True)),
                ('nUrlA', models.IntegerField(blank=True, db_column='nUrlA', null=True)),
                ('nUrlB', models.IntegerField(blank=True, db_column='nUrlB', null=True)),
                ('nUrlC', models.IntegerField(blank=True, db_column='nUrlC', null=True)),
                ('saved_path', models.CharField(blank=True, max_length=200, null=True)),
                ('saved_name', models.CharField(blank=True, max_length=200, null=True)),
                ('usr_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('gather_st_time', models.DateTimeField(blank=True, null=True)),
                ('gather_en_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls_breakdown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsKeywordNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('nurl', models.IntegerField(blank=True, db_column='nUrl', null=True)),
                ('top300', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls_keyword_number',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('function', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('phrase', models.TextField(blank=True, null=True)),
                ('pol', models.CharField(blank=True, max_length=20, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('nurl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pol_phrase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('function', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('fun_count', models.IntegerField(blank=True, null=True)),
                ('pos_num', models.IntegerField(blank=True, null=True)),
                ('neg_num', models.IntegerField(blank=True, null=True)),
                ('pos_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('neg_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('nurl', models.IntegerField(blank=True, null=True)),
                ('crawltime', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pol_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urllist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('publishtime', models.DateTimeField(blank=True, null=True)),
                ('crawled', models.CharField(blank=True, max_length=5, null=True)),
                ('crawltime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'urllist',
                'managed': False,
            },
        ),
    ]
