# Generated by Django 2.2.5 on 2019-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Htdocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('publishtime', models.DateTimeField(blank=True, null=True)),
                ('nlike', models.IntegerField(blank=True, null=True)),
                ('nreply', models.IntegerField(blank=True, null=True)),
                ('iscommercial', models.CharField(blank=True, max_length=5, null=True)),
                ('htmltext', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'htdocs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urllist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('endate', models.DateField(blank=True, null=True)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('publishtime', models.DateTimeField(blank=True, null=True)),
                ('crawled', models.CharField(blank=True, max_length=5, null=True)),
                ('crawltime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'urllist',
                'managed': False,
            },
        ),
    ]
