# Generated by Django 2.2.5 on 2019-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ByWhat', models.CharField(max_length=200, null=True)),
                ('keywordA', models.CharField(max_length=200, null=True)),
                ('keywordB', models.CharField(max_length=200, null=True)),
                ('keywordC', models.CharField(max_length=200, null=True)),
                ('channelA', models.CharField(max_length=200, null=True)),
                ('channelB', models.CharField(max_length=200, null=True)),
                ('channelC', models.CharField(max_length=200, null=True)),
                ('channelD', models.CharField(max_length=200, null=True)),
                ('periodA', models.CharField(max_length=200, null=True)),
                ('periodB', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
