# Generated by Django 2.2.5 on 2019-09-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_select'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Select',
            new_name='Choice',
        ),
    ]
