# Generated by Django 2.2.5 on 2019-09-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190904_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'managed': False},
        ),
    ]
