# Generated by Django 2.2.5 on 2019-09-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190905_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='polls_choice',
        ),
    ]
