# Generated by Django 2.2.5 on 2019-09-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ByWhat', models.CharField(blank=True, db_column='ByWhat', max_length=200, null=True)),
                ('keywordA', models.CharField(blank=True, db_column='keywordA', max_length=200, null=True)),
                ('keywordB', models.CharField(blank=True, db_column='keywordB', max_length=200, null=True)),
                ('keywordC', models.CharField(blank=True, db_column='keywordC', max_length=200, null=True)),
                ('channelA', models.CharField(blank=True, db_column='channelA', max_length=200, null=True)),
                ('channelB', models.CharField(blank=True, db_column='channelB', max_length=200, null=True)),
                ('channelC', models.CharField(blank=True, db_column='channelC', max_length=200, null=True)),
                ('channelD', models.CharField(blank=True, db_column='channelD', max_length=200, null=True)),
                ('periodA', models.CharField(blank=True, db_column='periodA', max_length=200, null=True)),
                ('periodB', models.CharField(blank=True, db_column='periodB', max_length=200, null=True)),
                ('nUrl', models.IntegerField(blank=True, db_column='nUrl', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
